git submodule add https://github.com/fishlamp/FishLamp-Objc-Core FishLamp/FishLamp-Objc-Core
git submodule add https://github.com/fishlamp/FishLamp-Objc-UnifiedAsync FishLamp/FishLamp-Objc-UnifiedAsync
git submodule add https://github.com/fishlamp/FishLamp-Objc-Services FishLamp/FishLamp-Objc-Services
git submodule add https://github.com/fishlamp/FishLamp-Objc-Containers FishLamp/FishLamp-Objc-Containers
git submodule add https://github.com/fishlamp/FishLamp-Objc-Logger FishLamp/FishLamp-Objc-Logger
git submodule add https://github.com/fishlamp/FishLamp-Objc-CodeGenerator FishLamp/FishLamp-Objc-CodeGenerator
git submodule add https://github.com/fishlamp/FishLamp-Objc-UnitTestRunner FishLamp/FishLamp-Objc-UnitTestRunner
git submodule add https://github.com/fishlamp/FishLamp-Objc-ModelObject FishLamp/FishLamp-Objc-ModelObject
git submodule add https://github.com/fishlamp/FishLamp-Objc-Networking FishLamp/FishLamp-Objc-Networking
git submodule add https://github.com/fishlamp/FishLamp-Objc-Encoding FishLamp/FishLamp-Objc-Encoding
git submodule add https://github.com/fishlamp/FishLamp-Objc-Storage FishLamp/FishLamp-Objc-Storage
git submodule add https://github.com/fishlamp/FishLamp-Objc-CommandLineProcessor FishLamp/FishLamp-Objc-CommandLineProcessor
git submodule add https://github.com/fishlamp/FishLamp-Objc-ActivityLog FishLamp/FishLamp-Objc-ActivityLog
git submodule add https://github.com/fishlamp/FishLamp-Objc-Authentication FishLamp/FishLamp-Objc-Authentication
git submodule add https://github.com/fishlamp/FishLamp-Objc-CodeBuilder FishLamp/FishLamp-Objc-CodeBuilder
git submodule add https://github.com/fishlamp/FishLamp-Objc-ColorUtils FishLamp/FishLamp-Objc-ColorUtils
git submodule add https://github.com/fishlamp/FishLamp-Objc-GeometryUtils FishLamp/FishLamp-Objc-GeometryUtils
git submodule add https://github.com/fishlamp/FishLamp-Objc-BundleUtils FishLamp/FishLamp-Objc-BundleUtils
git submodule add https://github.com/fishlamp/FishLamp-Objc-UnitTests FishLamp/FishLamp-Objc-UnitTests
git submodule add https://github.com/fishlamp/FishLamp-Objc-Timer FishLamp/FishLamp-Objc-Timer
git submodule add https://github.com/fishlamp/FishLamp-Objc-Strings FishLamp/FishLamp-Objc-Strings
git submodule add https://github.com/fishlamp/FishLamp-Objc-Utils FishLamp/FishLamp-Objc-Utils
git submodule add https://github.com/fishlamp/FishLamp-Objc-Compatibility FishLamp/FishLamp-Objc-Compatibility
git submodule add https://github.com/fishlamp/FishLamp-Objc-Experimental FishLamp/FishLamp-Objc-Experimental
git submodule add https://github.com/fishlamp/FishLamp-External FishLamp/FishLamp-External
git submodule add https://github.com/fishlamp/FishLamp-Objc-Files FishLamp/FishLamp-Objc-Files
git submodule add https://github.com/fishlamp/FishLamp-Images FishLamp/FishLamp-Images
git submodule add https://github.com/fishlamp/FishLamp-Objc-Notifications FishLamp/FishLamp-Objc-Notifications
git submodule add https://github.com/fishlamp/FishLamp-OSX-ActivityLogViewController FishLamp/FishLamp-OSX-ActivityLogViewController
git submodule add https://github.com/fishlamp/FishLamp-OSX-BreadcrumbBarView FishLamp/FishLamp-OSX-BreadcrumbBarView
git submodule add https://github.com/fishlamp/FishLamp-OSX-Documents FishLamp/FishLamp-OSX-Documents
git submodule add https://github.com/fishlamp/FishLamp-OSX-ErrorViewController FishLamp/FishLamp-OSX-ErrorViewController
git submodule add https://github.com/fishlamp/FishLamp-OSX-FileDropTableViewController FishLamp/FishLamp-OSX-FileDropTableViewController
git submodule add https://github.com/fishlamp/FishLamp-OSX-HttpController FishLamp/FishLamp-OSX-HttpController
git submodule add https://github.com/fishlamp/FishLamp-OSX-TextViewController FishLamp/FishLamp-OSX-TextViewController
git submodule add https://github.com/fishlamp/FishLamp-OSX-TextViewLogger FishLamp/FishLamp-OSX-TextViewLogger
git submodule add https://github.com/fishlamp/FishLamp-OSX-Utils FishLamp/FishLamp-OSX-Utils
git submodule add https://github.com/fishlamp/FishLamp-OSX-ViewController FishLamp/FishLamp-OSX-ViewController
git submodule add https://github.com/fishlamp/FishLamp-OSX-Views FishLamp/FishLamp-OSX-Views
git submodule add https://github.com/fishlamp/FishLamp-OSX-WizardViewController FishLamp/FishLamp-OSX-WizardViewController
git submodule add https://github.com/fishlamp/FishLamp-UI-Animations FishLamp/FishLamp-UI-Animations
git submodule add https://github.com/fishlamp/FishLamp-UI-BoxArranger FishLamp/FishLamp-UI-BoxArranger
git submodule add https://github.com/fishlamp/FishLamp-UI-Drawable FishLamp/FishLamp-UI-Drawable
git submodule add https://github.com/fishlamp/FishLamp-UI-View FishLamp/FishLamp-UI-View
git submodule add https://github.com/fishlamp/FishLamp-UI-ViewController FishLamp/FishLamp-UI-ViewController
